# Use a Node base image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Define build arguments
# Vite required the ENV variables to be passed as build arguments
ARG BACKEND_URL
ARG SOCKETS_URL
ARG BACKEND_PORT
ARG SOCKETS_PORT
ARG IS_PRODUCTION

# Make them available as environment variables during build
ENV VITE_BACKEND_URL=$BACKEND_URL
ENV VITE_SOCKETS_URL=$SOCKETS_URL
ENV VITE_BACKEND_PORT=$BACKEND_PORT
ENV VITE_SOCKETS_PORT=$SOCKETS_PORT
ENV VITE_IS_PRODUCTION=$IS_PRODUCTION

# Install pnpm globally
RUN npm install -g pnpm

# Copy only package.json and pnpm-lock.yaml first to leverage Docker caching
COPY package.json pnpm-lock.yaml ./

# Install dependencies and ensure optional dependencies are skipped
RUN pnpm install 

# Copy the rest of the application
COPY . .

# Build the app
RUN pnpm build

# Serve the build with Nginx
FROM nginx:stable
# Copy the dev config directly to conf.d
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]