services:
  frontend:
    image: lucasremigio/frontend:${TAG}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount SSL certificates as read-only
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro # Ensure the live folder is accessible

  websockets:
    image: lucasremigio/websockets:${TAG}
    ports:
      - "${SOCKETS_PORT}:${SOCKETS_PORT}"
    environment:
      - PORT=${SOCKETS_PORT}
      - FRONTEND_URL=${FRONTEND_URL}

  app:
    image: lucasremigio/app:${TAG}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # depends_on:
    #   - db
    environment:
      - IS_PRODUCTION=true
      - PORT=${BACKEND_PORT}
      - REMOTE_DB_URL=${REMOTE_DB_URL}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysql-container:3306/wallet_tracker
      - FRONTEND_URL=${FRONTEND_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_IN_SECONDS=${JWT_EXPIRATION_IN_SECONDS}
      # db:
      #   image: mysql:8
      #   container_name: mysql-container
      #   environment:
      #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #     MYSQL_DATABASE: wallet_tracker
      #   ports:
      #     - "3306:3306"
      #   volumes:
      #     - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
