name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Frontend Image
        run: |
          docker build -f frontend/Dockerfile \
            --build-arg VITE_BACKEND_URL=${{ vars.BACKEND_URL }} \
            --build-arg VITE_SOCKETS_URL=${{ vars.SOCKETS_URL }} \
            -t lucasremigio/frontend:${{ github.sha }} ./frontend

      - name: Build Backend Image
        run: |
          docker build -f backend/Dockerfile -t lucasremigio/app:${{ github.sha }} ./backend

      - name: Build Websocket Image
        run: |
          docker build -f sockets/Dockerfile -t lucasremigio/websockets:${{ github.sha }} ./sockets

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Frontend Image
        run: docker push lucasremigio/frontend:${{ github.sha }}

      - name: Push Backend Image
        run: docker push lucasremigio/app:${{ github.sha }}

      - name: Push Websocket Image
        run: docker push lucasremigio/websockets:${{ github.sha }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose file to VPS
        run: scp -o StrictHostKeyChecking=no docker-compose.prod.yaml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/docker-compose.prod.yaml

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

            # On the server, only save the tag, in case we need to restart manually
            echo "TAG=${{ github.sha }}" > .env

            export TAG=${{ github.sha }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_USER=${{ secrets.DB_USER }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export REMOTE_DB_URL=${{ secrets.REMOTE_DB_URL }}

            export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export JWT_EXPIRATION_IN_SECONDS=${{ secrets.JWT_EXPIRATION_IN_SECONDS }}

            # Use the repository variable
            export FRONTEND_URL=${{ vars.FRONTEND_URL }}
            export BACKEND_URL=${{ vars.BACKEND_URL }}
            export SOCKETS_URL=${{ vars.SOCKETS_URL }}

            docker image prune -a -f
             
            docker pull lucasremigio/frontend:${{ github.sha }}
            docker pull lucasremigio/app:${{ github.sha }}
            docker pull lucasremigio/websockets:${{ github.sha }} 

            docker compose -f docker-compose.prod.yaml up -d
          EOF
