name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Frontend Image
        run: |
          docker build -f frontend/Dockerfile -t lucasremigio/frontend:${{ github.sha }} ./frontend

      - name: Build Backend Image
        run: |
          docker build -f backend/Dockerfile -t lucasremigio/app:${{ github.sha }} ./backend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Frontend Image
        run: docker push lucasremigio/frontend:${{ github.sha }}

      - name: Push Backend Image
        run: docker push lucasremigio/app:${{ github.sha }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose file to VPS
        run: scp -o StrictHostKeyChecking=no docker-compose.prod.yaml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/docker-compose.prod.yaml

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'

            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "TAG=${{ github.sha }}" >> .env

            docker image prune -a -f
             
            docker pull lucasremigio/frontend:${{ github.sha }}
            docker pull lucasremigio/app:${{ github.sha }}

            docker compose -f docker-compose.prod.yaml up -d
          EOF
